<!DOCTYPE html>
<html>
  <head>
    <title>CS 2308</title>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="../../style/pe.css">
  </head>
  
  <?php include "../../head.php"; ?>
  <nav><?php include "../../nav.php"; ?></nav>
  
  <body>
     
    <div class="main">
      
      <br>
      
      <div class="boxed">
        <h2><a href="https://projecteuler.net/problem=2">Problem 2: Even Fibonacci numbers</a></h2>
        <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:<br>
          <center>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</center><br>
          By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
      </div>
      
      <div class="boxed">
        <p>I first solved this problem September 2nd, 2014 in my AP Computer Science class in highschool. I do not have the original code I wrote, but I have redone the solution and included it below.</p>
        
        <p>This problem was also fairly easy. I simply generated Fibonacci numbers until they reached four million, and added them to a sum if they were even. This code could also be optimized, but I prefer this simple version.</p>
         
        <div class="code-snippet">
          <pre><code><xmp><?php include "002.cpp"; ?></xmp></code></pre>
        </div>
        
        Answer: <code>4613732</code>
        
      </div>
      
    </div>
    
  </body>
  
</html>

